mode = "dark"
accent = "#009fff"
selection = "#19283c"
muted = "#737373"

background = "#0a0a0a"
dark_background = "#050505"
darker_background = "#000000"
lighter_background = "#1d1d1d"

foreground = "#fafafa"
dark_foreground = "#a3a3a3"
light_foreground = "#ffffff"
bright_foreground = "#ffffff"

red = "#ff2e3f"
yellow = "#ffca00"
orange = "#ffab16"
green = "#0dbe4e"
cyan = "#08c0ef"
blue = "#009fff"
magenta = "#e130ac"
brown = "#9c6534"

bright_red = "#ff2e3f"
bright_yellow = "#ffca00"
bright_green = "#86c427"
bright_cyan = "#08c0ef"
bright_blue = "#009fff"
bright_magenta = "#e130ac"
